
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: SnykSecurityScan@0
  inputs:
    serviceConnectionEndpoint: 'snyk'
    testType: 'app'
    severityThreshold: 'high'
    monitorOnBuild: false
    failOnIssues: true

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'mikebroomfield/az-snake'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

