trigger:
- dockle

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'mikebroomfield/az-snake'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    
- script: |
  apt-get update    
  apt-get install -y rpm curl wget
  VERSION=$(
  curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | \
  grep '"tag_name":' | \
  sed -E 's/.*"v([^"]+)".*/\1/'
  )
  if [[ "${{ parameters.ignoreCheckpoints }}" -eq "" ]]; then
    CHECKPOINTS_TO_IGNORE=""
  else
    CHECKPOINTS_TO_IGNORE=$(echo " ${{ parameters.ignoreCheckpoints }}" | tr -s " " " " | sed "s/[[:space:]]/ -i /g")
  fi
  wget https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.tar.gz
  tar zxvf dockle_${VERSION}_Linux-64bit.tar.gz
  
  # Build report
  ./dockle -f json -o dockle-report.json mikebroomfield/az-snake:$(Build.BuildId)
  
  # Print report
  ./dockle --exit-code 0 mikebroomfield/az-snake:$(Build.BuildId)
  
  # Fail on critical checkpoints
  ./dockle --exit-code 1 --exit-level fatal mikebroomfield/az-snake:$(Build.BuildId) >> /dev/null
  
  displayName: 'Dockle Check Container'