# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'mikebroomfield/az-snake'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- script: |
      apt-get update
      apt-get install -y rpm curl wget
      VERSION=$(
      curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | \
      grep '"tag_name":' | \
      sed -E 's/.*"v([^"]+)".*/\1/'
      )
      wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
      tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
      # Build report
      ./trivy --no-progress -f json mikebroomfield/az-snake:$(Build.BuildId)
      # Print report
      ./trivy --exit-code 0 --no-progress --severity HIGH mikebroomfield/az-snake
      # Fail on critical vulnerabilities
      ./trivy --exit-code 1 --no-progress --severity HIGH mikebroomfield/az-snake
  displayName: 'Trivy Check Container'
